---
title: "field-safety"
author: "Krishnapriya Tamma"
date: "13 July 2016"
output: html_document
---

# Guidelines for safety in field

These are some general guidelines to being safe in field and to have a fantastic stay in the forest! 

## Instructions to team leaders

First and foremost, please be courteous to all field staff. This is very important. Their needs are just as important as ours, and they have the same access to all field equipment as we do. Share all equipment, food etc with them. 

Please give a quick orientation to all members who join the team, and reiterate the sexual harassment policy and the safety guide. Please provide them with the list of emergency contacts and the emergency kits. Obtain the contacts of police/magistrate of the area where you work. 

Please ensure that everyone, including forest department staff and local village guides all stay in tents - especially when mosquitoes are all around. Also carry extra mosquito repellants (Odomos etc) so you can share with them. 

Emergency kits - Electrol, paracetamol, odomos, cetrizine, band-aids, five-star - to be given to all members. Also keep the emergency medical kit in camp-site where accessible to all. 

Informal advice - please take meat as part of diet esp if staying outside PA for the field assistants. Ask DFO if OK to take dried fish inside. Please DO NOT encourage fishing inside PA.

Informal advice - if you stay in village, please clean accommodation, spend time explaining to village council what you do and thank them for letting you stay. Please be mindful of what you say and do when you stay in a village. 

## General instructions:

0. First and foremost, please be courteous to all field staff. This is very important. Their needs are just as important as ours, and they have the same access to all field equipment as we do. Share all equipment, food etc with them. 
1.  Please DO NOT handle snakes, scorpions or other animals apart from rodents in field 
2.	Please report to the team leader if you have to head away more than 200m from camp, for any reasons
3.	Please DO NOT walk alone in the forest at night. There are many elephants in Indian forest landscapes
4.	Avoid walking alone in the forest even during the day. Take a field guide or another experienced team member when walking in forest. DO NOT leave pre-existing trails. Beware of elephants!
5.	Check all shoes and socks before wearing them since scorpions may sometimes be found inside!
6.	Always carry water in field, and the emergency kit that will be given to you
7.	In your bag you must always have water bottle, emergency food, torch, and an extra Tshirt
8.	Ensure that the water quality is good at camp site. If very muddy or bad, make alternative arrangements or make clay based filters. (We also have drops that can be added to make water potable, ask Team leader). 
9.	DO NOT wear camouflage clothes in the forest as many of these places have issues of insurgency
10.	Ensure that someone from another team knows where your team is headed off every day. Everyone in the team should know where everyone else is going. 
11.	Ensure that all of you have the following information on you at all times: emergency contact, your blood group and the contact of everyone else in team. Please take the effort to try and remember you team members blood type and allergy details, if any.
12.	No drinking and drugs during field work. Blanket ban. 
13.	If you like photographing - please be sensitive when filming or photographing local people, customs and events. First, ask permission! 

## Check-list for field trips
   * Permit letter
   * ID Card
   * Flash lights, spare batteries, etc
   * Approprtiate clothing (check the expected weather)
   * Water bottle
   * Sufficient money, atm/credit card, etc.
   * Binoculars, scopes, bird books (optional)
   * Book accommodation. Know (& how) the destination, local maps, etc.
   * First-Aid kit
   * Make sure you have insurance (ask adviser)
