---
title: "sexual-harassment-policy"
author: "Krishnapriya Tamma"
date: "13 July 2016"
output: html_document
---

# Policy on sexual harassment 

Our lab strives to be gender neutral both in field and off it. It is important to put in some form of a framework in place so that we have a system to help us feel safer. 

The following can be considered as informal guidelines as pertaining to sexual harassment that any team member can face as part of the work, either at IISc or outside (e.g., field). This policy is gender neutral that is applicable to males and female employees and volunteers of the lab. 

*Note to team leader in the field*:  This is applicable for field projects which typically have a senior lab member leading the field project. Team leaders must make note of the name and phone number of the law enforcing office closest to your field station. This can be the police or the district magistrate as you deem necessary. Team leader should have list of names of phone numbers at all times and share with other team members. Team leader should also have list of names and phone numbers of all team members and their emergency contacts at all times. Team leader must also ensure that the volunteer or assistant has read and understood this document before s/he joins the team, and is aware of all the people mentioned in the document.

### Scope of the policy
This policy is applicable to 
   * All people associated with the lab (formally employed and volunteers)
   * All allegations of sexual harassment by an employee/volunteer against another employee/volunteer
   * All allegations of sexual harassment by an non-employee against the employee/volunteer when they were in active duty on the project
   * All allegations of sexual harassment by an employee against non-employee while on active duty (Note: these can also be taken to the police).

### What constitutes sexual harassment?
Sexual harassment includes any unwelcome sexually determined behaviour (either direct or indirect) as described below:

  * Physical contact or advances
  * A demand or request for sexual favours in exchange for other favours   
  * Sexually coloured remarks 
  * Showing pornography
  * Other physical, verbal or non-verbal (showing of images etc) conduct of a sexual nature

The following circumstances also amount to sexual harassment

  * Implied or express promise of preferential treatment/threat of detrimental treatment in employment
  * Creation of intimidating, offensive or hostile work environment
  * Humiliating treatment likely to affect health or safety

The following actions can be deemed as sexual harassment, in detail:

  * Unwelcome sexual advances - with or without physical touching
  * Sexual jokes (written or verbal), lewd stares, written or verbal reference to sexual conduct, gossip about one’s sex life 
  * Comments on one’s appearance, or sexual activity
  * Displaying sexually suggestive objects, images, videos or sounds
   * Unwelcome leering, physical contact, gestures or comments
   * Discussion of one’s sex life or enquiries into the same
   * Lewd comments on members not present in the vicinity and comments on their sex liife

This is not an exhaustive list, and there may be certain situations that are not part of the framework outlined above that could constitute harassment. We encourage you to talk to the team leaders or the PI if you are uncertain. Often, we assume that we are over-reacting, although we may be justified in feeling violated. Please make sure to talk with any of us that you trust to clarify any doubts. 

As a group of people we will take all precautions to prevent sexual harassment within the purview of this project. These steps include:

  * Circulating this policy to all the people in the project and ensuring that they are aware of all the details 
  * Ensuring that everyone is aware of the presence of this policy and that this is easily accessible to all in the team
  * Ensuring that the issue of sexual harassment is raised in all meetings both on and off field so that team members are comfortable discussing these issues
  * Ensuring that the names and contact details of all the contact persons is shared with all team members and that they are accessible

## What is a 'consent'? 

Consent is defined as a clear and unambiguous agreement expressed in mutually understandable words or gestures to engage in a particular sexual (in this case) activity with another person. Consent is limited to the activity under discussion, and does not extend indefinitely. Consent must be voluntarily given, and not under influence of alcohol, drugs or other substances that may hamper the judgement of the person. Consent is not valid if the person is subject to emotional or psychological pressure, intimidation or fear. Previous consent cannot be presumed to constitute consent at any other time, or for any other activity. Consent can be withdrawn at any time. The absence of ‘NO’ does not mean ‘YES’. 

Note that the intent of the perpetrator is irrelevant. What matters is the impact of the actions and therefore, to determine whether or not harassment occurred must be taken from the victim’s perspective. 


## Filing of the complaints

This is an informal policy document, and when a complaint is made, it is appropriate that it then be handed over to the __Sexual Harassment Complaint Committee__ of IISc (http://www.iisc.ernet.in/shcc/complaints.php). Since the volunteers may not be employees of the committee, it has to pass to the PI or a senior student member. Since most employees and volunteers are likely to be in field when any untoward incident occurs, please follow the chain of command to make complaints. Complains may be lodged either verbally or in written. In field, please pass on your complaints to the Team Leader / PI directly. 

If the complaint is against the team leader, please pass on your complaint to Krishnapriya Tamma (KT) or Vishwesha Guttal (VG) at Bangalore. If you are unable to reach them, please complaint to any member of the team that you trust, who will then relay the information to KT/VG. If the scenario is severe, please leave field and come to the nearest town, and call KT/VG. All travel and stay expenses will be borne by the project. 

If the complaint is against KT, please lodge complaint with Dr. Vishwesha Guttal (VG), who is KT’s current advisor, after notifying the team leader. VG will then take the complaint forward and take appropriate action. If the complaint is against VG, please lodge complaint with other faculty member of the CES (or at a higher level at IISc). A couple of contacts have been provided at the end of this document along with all other contact details. 

All complaints will be brought before the institute ‘Internal Complaints Committee’ that will investigate the complaints. 

If the problem is severe, and if you fear for your safety please remove yourself from the situation till appropriate measures have been taken. Please do not take any risks, or ‘try to adjust’. 

## Contacts

__Krishnapriya Tamma__
Email: priya.tamma@gmail.com
Phone: 9886553088

__Vishwesha Guttal__
Email: guttal@ces.iisc.ernet.in
Phone: 080-22932872 or 23605797. Call the mobile number in case of emergency.
(if emergency, call CES office 080-23600985 and ask to be connect to Vishu)

__IISc contacts__
Chairman, SHCC (SEXUAL HARASSMENT COMPLAINTS COMMITTEE)
Prof Sandhaya S.V, MRDG -- Chairperson 
Email: sandhya@mrdg.iisc.ernet.in

## Some issues to think

What should a team member do if he or she is casually told about a sexual harassment incident; i.e. not in the form of a complain? Should the team member mandatorily report it onwards? Should the team member try to investigate the incident? Should the team member actively provide interim relief?

## Further reading
[Crossing the Line, Sexual Harassment at School](http://www.aauw.org/files/2013/02/Crossing-the-Line-Sexual-Harassment-at-School.pdf)

[Preventing Sexual Harassment at UW-W](http://www.uww.edu/adminaffairs/hr/employee-training-development/preventing-sexual-harassment)

[Online training on Sexual Harassment](http://training.newmedialearning.com/psh/uwiscwhite/index.htm)

[A simple test](https://www.surveymonkey.com/r/62YM32Y)