---
title: "writing tips"
author: "Vishwesha Guttal"
date: "10/7/2016"
output: html_document
---

#Tips to write short synthesis

### Before you write 

Decide who is your target audience. We are often thinking of scientific audience who may not necessarily be experts in the paper you are summarising. From the summary you provide, the reader must be able to get a gist of the paper without having read the paper!

Before you write, [read the paper thoroughly](https://github.com/guttal/tee-tools/blob/master/how-to-read-papers.Rmd). Make a list of a few salient points that you want to raise. 

Write in your own words. Do not copy text from the paper. There is no need for you to cite or read additional material as this should be a summary of the current paper only. 

### Structure of the write up 

You can keep in mind this outline while structuring your summary
   
   * Background of the topic 
   * Describe what they did + Findings/Results (can also go in at the end of the background paragraph)
   * Provide your opinion on the paper
    
### Clarity, Flow and Coherence

## References

[20 ways to improve your writing](http://academiclifehistories.weebly.com/blog/20-ways-to-improve-your-paper-a-journal-club-introspective)

